

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: distsim-backend
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://host.docker.internal:27017/distributed-sim
      - JWT_SECRET=${JWT_SECRET}
      - CLIENT_URL=http://frontend:5173
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: distsim-frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  ollama_data: